### ISSUE TITLE
Current rev (89b0d34) does not compile

### ISSUE THREAD

**Issue by jpotier** [krayon/ratslap#1]
```
log.h:44:13: warning: inline function ‘std_output’ declared but never defined
  inline void std_output(FILE *strm, const char *srcfile, const int line
```

leading to a

```
main.o: In function `mouse_hid_detach_kernel':
/tmp/ratslap/main.c:596: undefined reference to `std_output'
/tmp/ratslap/main.c:601: undefined reference to `std_output'
main.o: In function `mouse_hid_attach_kernel':
/tmp/ratslap/main.c:622: undefined reference to `std_output'
/tmp/ratslap/main.c:617: undefined reference to `std_output'
main.o: In function `main':
/tmp/ratslap/main.c:745: undefined reference to `std_output'
main.o:/tmp/ratslap/main.c:501: more undefined references to `std_output' follow
collect2: error: ld returned 1 exit status
make: *** [Makefile:176: ratslap] Error 1
```

**Comment by krayon** [comment]
gcc 5?

**Comment by krayon** [comment]
47971645e89f873d79d9d4837f60415123678b83 might fix it ... though I should probably explicitly tell GCC some stuff ...

**Comment by jpotier** [comment]
ratslap [master●] gcc -v
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/lto-wrapper
    Target: x86_64-pc-linux-gnu
    Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
    Thread model: posix
    gcc version 6.2.1 20160830 (GCC)

Current revision (commit 2093371b2316f26c4bca60f8ec8a6b75ea6029c1) does compile \o/

**Comment by krayon** [comment]
( tracked as https://bugs.qdnx.org/issue/103 )
