### ISSUE TITLE
All buttons with "tab" doesn't work anymore

### ISSUE THREAD

**Issue by NerosTie** [krayon/ratslap#12]
On Arch, with the last updates, it seems that every buttons which use a "tab" (example: "LeftCtrl+Tab") doesn't work anymore. I have no idea why, it's something new. When I push the button it's only a "tab", but if I stay pressed, it works but it's not the behaviour you want. No issues with "LeftCtrl+C". No issues on Windows.

Maybe it's not related with ratslap, it could be a firmware issue.

Edit: I think it's from libinput which has been updated recently, but I need confirmation.

**Comment by kaetahr** [comment]
Can confirm I have the same problem, and I'm not using ratslap. It could be libinput.

**Comment by mohanagh** [comment]
Can confirm. Even LeftCtrl+T is not working. Till then, I'll downgrade libinput and try.

**Comment by NerosTie** [comment]
Definitely a bug from libinput: https://bugs.freedesktop.org/show_bug.cgi?id=104030

I close this issue, it's unrelated to ratslap.

**Comment by krayon** [comment]
Sorry I didn't get to this sooner.

@NerosTie : Thanks for the report; @kaetahr @mohanagh : Thanks for the helpful comments :)

**Comment by NerosTie** [comment]
It's even fixed in libinput 1.9.4 now ;)
