### ISSUE TITLE
Media Commands

### ISSUE THREAD

**Issue by cc201129r** [krayon/ratslap#13]
can i remap the mouse button for media playback? how i configure it? still noob :)

**Comment by txgruppi** [comment]
@cc201129r I tested the _UNKOWN:??_ keys and found the keys for `Vol+` `Vol-` `Mute` but I could not find a key for `Play/Pause`.

The keys are:

| Key string | Function |
| - | - |
| `UNKNOWN:7f` | Mute toggle |
| `UNKNOWN:80`| Vol+ |
| `UNKNOWN:81` | Vol- |

As an example, this is the command I use:

```sh
# g4 Mute
# g6 Vol-
# g7 Vol+
ratslap \
  -m f5 \
  --colour red \
  -r 500 \
  --g4 "UNKNOWN:7f" \
  --g5 Button5 \
  --g6 "UNKNOWN:81" \
  --g7 "UNKNOWN:80" \
  --g8 ModeSwitch \
  --g9 Button9 \
  -s F5

```

**Comment by txgruppi** [comment]
@cc201129r I found a way to make `Play/Pause` work!

Short version: I mapped F19 to `Play/Pause` and mapped `UNKNOWN:68` (F19) to button 5

Long version:

1. Run `cd /usr/share/X11/xkb/symbols`
1. Run `sudo vim inet`
1. Find line starting with `    key <FK18>`
1. Add below the FK18 line: `key <FK19>   { [ XF86AudioPlay, XF86AudioPause ] };`
1. Save the file and close vim
1. Run `setxkbmap -layout <yout layout> -variant <your variant>` (if you don't know the args you can run `setxkbmap -query` to see it)
1. run `ratslap` mapping `UNKNOWN:68` to the button you want to have the `Play/Pause` action

**Comment by krayon** [comment]
Yes as @txgruppi suggests ( and similar to what I describe in issue #17 ) you can map other key combo's to the button and media actions to that key combo. [xbindkeys(1)](https://linux.die.net/man/1/xbindkeys) is another option for doing this.

The only keys that are available are those defined in the USB HID Keyboard set. These include volume up, down and mute, but not other media functions ( as @txgruppi also discovered ).

**Comment by krayon** [comment]
@txgruppi : Be aware the rest of the buttons were mapped out in a recent update so you'll have to change your config to not use the UNKNOWN names.
