### ISSUE TITLE
Help needs priority

### ISSUE THREAD

**Issue by ChillyWillyGuru** [krayon/ratslap#15]
If you run 'ratslap -h' normally such that the user doesn't have access to the usb, you get an error about not being able to do any usb ops rather than the help. Help should ALWAYS be available. I'd suggest checking if the help option has been asked for first before anything else, and if so print the help and exit. Only if the user doesn't want help should it then try to get the usb.

**Comment by krayon** [comment]
TRACKED AS QB#122 : https://bugs.qdnx.org/issue/122

**Comment by krayon** [comment]
Branch: https://github.com/krayon/ratslap/tree/feature/isolatehelp

**Comment by krayon** [comment]
--listkeys also shouldn't require permissions

**Comment by krayon** [comment]
Fixed in commit 32ac5eceed2d03fde7bccf59515a3d7478752eb6

**Comment by krayon** [comment]
On roadmap ( https://bugs.qdnx.org/roadmap/proj5 ) for 0.2.3 release (ETA: 2018-07-13)
