### ISSUE TITLE
Open Calculator with mouse

### ISSUE THREAD

**Issue by raavier** [krayon/ratslap#17]
There is any way to set a button to open the gnome-calculator?

**Comment by krayon** [comment]
Not independently. You can however, generate a key combo that triggers an
action. You can map say `CTRL`-`ALT`-`L` to a button on the mouse, then in
Gnome (or your Desktop Environment (DE) / Window Manager (WM) of choice) map
`CTRL`-`ALT`-`L` to launch an application.

If for whatever reason your DE or WM doesn't support such an action, or you
don't use one, you could also use
[xbindkeys(1)](https://linux.die.net/man/1/xbindkeys) . It allows you to map
key presses to executing functions.

If you didn't want to use up a key combo, you can use a key that isn't even on
your keyboard (such as `F13`).
