### ISSUE TITLE
[Documentation] Basic How-To

### ISSUE THREAD

**Issue by jpotier** [krayon/ratslap#2]
I may be tired, but I don't get how to set say key `1` to my button `G4`. Actually, apart from calling `./ratslap -p f3-5` I don't understand how you actually set a modified mode. Should I edit the source code and recompile?

**Comment by krayon** [comment]
I hadn't actually pushed the modification functionality yet that's why. I'm doing it today.

**Comment by thomasluquet** [comment]
Same thing, for me, the documentation it is not really clear for me...

BTW, i try to make a draw of the mouse and the buttons, is it ok ?
(i can send you the .odg if you want)

![logitech-gaming-mice-g300s](https://cloud.githubusercontent.com/assets/145759/20092882/98241ee8-a59a-11e6-9734-8168b9449081.png)

**Comment by krayon** [comment]
@thomasluquet  That is one nice clean image! :D 

Unfortunately we can't actually reassign the mouse-up/down buttons.

We CAN reassign G8/G9 however.

I am adding a basic usage blurb in the README but could certainly use your
clean image to illustrate if it didn't have the wheel.

**Comment by krayon** [comment]
( tracked as https://bugs.qdnx.org/issue/110 )

**Comment by krayon** [comment]
commit:7b98287f8ed6f0aea29ff95e3c9a3dc0c3d56649

Add (basic) example Usage

commit:1f11e1c9546c03f08e89c7e8544eb0f1c9725349

Add another Usage example, with key bindings

**Comment by krayon** [comment]
@jpotier @thomasluquet : Let me know if you find the documentation in the
latest README helpful.

**Comment by jpotier** [comment]
The latest README is really useful and well written, I like the examples because they are on point and simple. Now, let's give it a try : )
