### ISSUE TITLE
dpishift: Unrecognised options: 500

### ISSUE THREAD

**Issue by Zush18** [krayon/ratslap#23]
I just buy a G300s and I'm using this tool, I love it but when trying to set the DPI for the DPI Shift I got this error message:
`prompt> sudo ratslap --modify F3 --dpishift 500`
```
Found Logitech G300s (046d:c246) @ 0x564e9540ade0
Detaching kernel driver...
Modifying Mode: F3
    Enabling DPI shift
20200809T000532-0500 [E]           main.c:01792:main            ERROR: Unrecognised options: 500
Saving Mode: F3
Attaching kernel driver...
```

And… it's fully need to output `ratslap --version` every time i run it?.
I installed from AUR

**Comment by krayon** [comment]
Fixed in commit fba0f6712d7161ee61c5e4f4c81353328a8dd951
 - Release: [0.4.1](https://github.com/krayon/ratslap/releases/0.4.1)

Thanks for the report @Zush18
