### ISSUE TITLE
Error [compiling]

### ISSUE THREAD

**Issue by loatth** [krayon/ratslap#25]
taha@linux:~/ratslap$ make
Generating tags file...
/bin/sh: 1: ctags: not found
No ctags found, skipping tags file...
RatSlap
Pulling from origin...
All updated.
Generating Changelog...
Generating git header file...
Package libusb-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libusb-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libusb-1.0' found
gcc -march=native  -O2 -pipe -Wall -Werror -ggdb   -DDEBUG -DINFO  -c "log.c" -o "log.o"
log.c:25:10: fatal error: stdio.h: No such file or directory
   25 | #include <stdio.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:270: log.o] Error 1

**Comment by krayon** [comment]
Hi @loatth ,

Sorry for the delay.

If you want to compile it yourself, you'll need at least the libc dev libraries and libusb. On Debian/Ubuntu, you will get MOST of what you need by installing their `build-essential` package I believe. Something like this should work:

```bash
sudo apt-get install build-essential libusb-1.0-0-dev
```

You can also download pre-compiled binaries from the [Releases](https://github.com/krayon/ratslap/releases) .

Let me know how you get on.

**Comment by krayon** [comment]
Assuming it worked :)
