### ISSUE TITLE
Key+Button possible?

### ISSUE THREAD

**Issue by case81** [krayon/ratslap#29]
Hi, thank you for the awesome tool!
It's currently not possible to make a mouse button do something like:
LeftShift+U+Button1
or
A+Button1
This would be useful in games, any chance this can be done or is it a limitation?

**Comment by vstyler96** [comment]
Why don't you try something like: `Key=A+Left-Click` or `Key=A+Button1`

**Comment by krayon** [comment]
>  This would be useful in games, any chance this can be done or is it a limitation?

No sorry, you can only assign modifiers with a key or button. The only way to do that would probably be to have software listening for certain keys then generating other keypresses and then make the mouse send `F13` or some other less used key.
