### ISSUE TITLE
G300s - no right or left mouse clicks (not related to ratslap code)

### ISSUE THREAD

**Issue by Synaxis** [krayon/ratslap#32]
Hi. for some weird reason my g300s just don't click. However on windows, with logitech g software, it works. but for example on ubuntu or windows with logitech software closed. it just doesn't work

Do you know what i can do to fix it ?

**Comment by Synaxis** [comment]
It's even detecting the clicks 

Event: time 1682946373.492035, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90006
Event: time 1682946373.492035, type 1 (EV_KEY), code 277 (BTN_FORWARD), value 1
Event: time 1682946373.492035, -------------- SYN_REPORT ------------
^[CEvent: time 1682946373.690030, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90006
Event: time 1682946373.690030, type 1 (EV_KEY), code 277 (BTN_FORWARD), value 0
Event: time 1682946373.690030, -------------- SYN_REPORT ------------
Event: time 1682946374.933268, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90006
Event: time 1682946374.933268, type 1 (EV_KEY), code 277 (BTN_FORWARD), value 1
Event: time 1682946374.933268, -------------- SYN_REPORT ------------
^[CEvent: time 1682946375.102190, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90006
Event: time 1682946375.102190, type 1 (EV_KEY), code 277 (BTN_FORWARD), value 0
Event: time 1682946375.102190, -------------- SYN_REPORT ------------

**Comment by krayon** [comment]
@Synaxis

If you're running Xorg/X11, what do you see when you click inside an `xev` window?

What do you have the button assigned to?

In the event you have the button assigned to something that your window manager and desktop environment may not act on (for example, a higher function key), then the button may appear to not work. The Logitech software in Windows is perhaps overriding that assignment, or talking to the device in a different fashion.

**Comment by Synaxis** [comment]
Thank you for the tips and for the help! Sorry for the late reply.
I fixed it by manually assigning the click again with logitech windows software! 

Now i just reboot to ubuntu and everything is perfect, also on windows with or without logitech software.

Also thanks for the ratslap code.
