### ISSUE TITLE
Doube G5 and G4

### ISSUE THREAD

**Issue by mccbdim** [krayon/ratslap#6]
when i set control configuration in dota2 to binding G7 and G6 buttotns it refers to G5 and G4 respectively. before i run the ratslap i try this script before :

`xinput list | grep G300`

then 

```
#!/bin/sh
DEVICE_ID=$(xinput list |  grep "Logitech Gaming Mouse G300" | grep keyboard | sed 's/.*id=\([0-9]*\).*/\1/')

if xinput -list-props $DEVICE_ID | grep "Device Enabled" | grep "1$" > /dev/null
then
        xinput set-int-prop $DEVICE_ID "Device Enabled" 8 0
fi
```
Do you have an idea for a solution?
Thank you !

**Comment by krayon** [comment]
What does the ratslap -pf3 (or whatever one you're using) show?

**Comment by krayon** [comment]
Assume no longer an issue?
