### ISSUE TITLE
How to use this tool ?

### ISSUE THREAD

**Issue by akred** [krayon/ratslap#7]
Hello,

Can you add documentation in order to explain how to install this tool please ?
For those who are not familiar to C language.
On my side, I have download sources and run the command "make", but I have an error which is : 
`/bin/sh: 1: ctags: not found`
`Makefile:170 : la recette pour la cible « ctags » a échouée`
`make: *** [ctags] Erreur 127`

Thanks for your help

**Comment by krayon** [comment]
TRACKED AS QB#117 : https://bugs.qdnx.org/issue/117

**Comment by krayon** [comment]
ctags shouldn't be needed to build, this is a mistake.

As a temporary work around, you can build using:
`make Changelog make.options.conf ratslap done`

**Comment by krayon** [comment]
FIXED IN RELEASE 0.2.1 ( d6dc4a00bb104f5e160d01c6561f7933a947fc6d )
